### ISSUE TITLE
Unauthorized & No response message

### ISSUE THREAD

**Issue by bstarr322** [paypal/PayPal-Ruby-SDK#285]
I've fully tested on sandbox for subscriptions by credit card, but **LIVE** does not work.
```
gem 'paypal-sdk-core', :git => 'https://github.com/paypal/sdk-core-ruby.git'
gem 'paypal-sdk-rest', :git => 'https://github.com/paypal/rest-api-sdk-ruby.git'

GIT
  remote: https://github.com/paypal/rest-api-sdk-ruby.git
  revision: 52a6688861023ebb2a3f5c9c9133844fe93b13c5
  specs:
    paypal-sdk-rest (1.6.0)
      multi_json (~> 1.0)
      xml-simple

GIT
  remote: https://github.com/paypal/sdk-core-ruby.git
  revision: 384b9ab6af7e23a2d5da9c9b84b3fc2ac1f4e5cb
  specs:
    paypal-sdk-core (0.3.4)
      multi_json (~> 1.0)
      xml-simple
```
paypal.yml
```
production:
  mode: live
  client_id: ENV['PAYPAL_CLIENT_ID_LIVE']
  client_secret: ENV['PAYPAL_CLIENT_SECRET_LIVE']
  app_id: ENV['PAYPAL_APP_ID_LIVE']
  username: ENV['PAYPAL_USERNAME_LIVE']
  password: ENV['PAYPAL_PASSWORD_LIVE']
  signature: ENV['PAYPAL_SIGNATURE_LIVE']
  verbose_logging: true
```
In this case I got this error and my environment is:
```
Failed. Response code = 401. Response message = Unauthorized. Response debug ID = 6feb5eaccf941, 6feb5eaccf941.

Ruby 2.4.0 OSX EI Capitan 10.11.6

```
But I succeeded by running **CURL** command to get OAuth token:
```
curl https://api.sandbox.paypal.com/v1/oauth2/token \
  -H "Accept: application/json" \
  -H "Accept-Language: en_US" \
  -u "client_id:secret" \
  -d "grant_type=client_credentials"
```
So I guessed the issue came back to wrong rest_endpoint and added `rest_endpoint: "https://api.paypal.com/v1"` into the `paypal.yml`.
But I got `Net::Timout` or `Unauthorized` 'for every API call.
e.g. when I creating a new plan:
```
plan = Plan.new({
        :name => self.unique_key,
        :description => self.title,
        :type => 'fixed',
        :payment_definitions => [{
          :name => self.unique_key,
          :type => 'REGULAR',
          :frequency_interval => self.interval_count.to_s,
          :frequency => self.interval.upcase,
          :cycles => '999',
          :amount => {
            :currency => 'USD',
            :value => (self.price / 100.0).ceil(2).to_s
          }
        }],
        :merchant_preferences => {
          :setup_fee => {
            :currency => 'USD',
            # :value => ((self.price / 100.0) * 0.029 + 0.3).ceil(2).to_s
            :value => 0
          },
          :cancel_url => packages_url,
          :return_url => profile_url + "#subscription",
          :max_fail_attempts => '0',
          :auto_bill_amount => 'YES',
          :initial_fail_amount_action => 'CONTINUE'
        }
})
if plan.create
      # do something
end
```
I got this error:
`Failed. Response code = 401. Response message = Unauthorized. Response debug ID = 6feb5eaccf941, 6feb5eaccf941.`

We are tight to the deadline for the production launch, so I'll appreciate your fast help.

Thank you @bstarr322
